### ISSUE TITLE
Importing BaseSettings failure

### ISSUE THREAD

**Issue by FidelusAleksander** [pydantic/pydantic-settings#109]
This only occurs on version 2.0.1

`pydantic-settings==2.0.1`

Previous version 2.0.0 works fine
Also I'm using python version 3.10.0

**Reproduction steps:**

1. pip install pydantic-settings==2.0.1
2. Run this code in python
`from pydantic_settings import BaseSettings`

Full traceback:
```
Traceback (most recent call last):
  File "/repos/pydantic-settings-test/main.py", line 1, in <module>
    from pydantic_settings import BaseSettings
  File "/repos/pydantic-settings-test/venv/lib/python3.10/site-packages/pydantic_settings/__init__.py", line 1, in <module>
    from .main import BaseSettings, SettingsConfigDict
  File "/repos/pydantic-settings-test/venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 30, in <module>
    class BaseSettings(BaseModel):
  File "/repos/pydantic-settings-test/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 171, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/repos/pydantic-settings-test/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 361, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/repos/pydantic-settings-test/venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py", line 97, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "/repos/pydantic-settings-test/venv/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "/repos/pydantic-settings-test/venv/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 221, in eval_type_lenient
    value = _make_forward_ref(value, is_argument=False, is_class=True)
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
What is your `pydantic` and `pydantic-core` version?

**Comment by FidelusAleksander** [comment]
pydantic==2.0.2
pydantic-settings==2.0.1
pydantic_core==2.1.2

I created a venv and only ran one pip install as stated in reproduction steps.

**Comment by hramezani** [comment]
What python version?

**Comment by FidelusAleksander** [comment]
3.10.0

**Comment by hramezani** [comment]
Please update your Python version to the latest version in `3.10`. e.g. `3.10.11`

**Comment by FidelusAleksander** [comment]
Yes it works on 3.10.11

However its confusing to me that on 3.10 the import works fine with
pydantic-settings version 2.0.0
but fails to import on 
2.0.1

**Comment by hramezani** [comment]
It's a change in `pydantic` that does not work with the older Python versions.
