### ISSUE TITLE
Failing tests in master?

### ISSUE THREAD

**Issue by chbndrhnns** [pydantic/pydantic-settings#687]
I am seeing these tests failing with 3e664300f38a4ad1e1ff4b431147f18d63930028.
Is this expected?

```
FAILED tests/test_docs.py::test_docs_examples[docs/index.md:1180-1197] - AttributeError: type object 'CliApp' has no attribute 'serialize'
FAILED tests/test_docs.py::test_docs_examples[docs/index.md:1928-1971] - ModuleNotFoundError: No module named 'azure'
FAILED tests/test_docs.py::test_docs_examples[docs/index.md:1977-2008] - ModuleNotFoundError: No module named 'azure'
FAILED tests/test_docs.py::test_docs_examples[docs/index.md:2018-2051] - ModuleNotFoundError: No module named 'azure'
FAILED tests/test_settings.py::test_annotated_with_type - pydantic_core._pydantic_core.ValidationError: 2 validation errors for Annot...
FAILED tests/test_settings.py::test_init_kwargs_alias_resolution_deterministic - AssertionError: assert {'last_name':...name': 'john'} == {'last_name':...na...
FAILED tests/test_settings.py::test_dotenv_env_prefix_env_without_prefix_ignored - AssertionError: assert {'foo': 'foo'} == {'foo': ''}
FAILED tests/test_settings.py::test_warns_if_config_keys_are_set_but_source_is_missing - Failed: DID NOT WARN. No warnings of type (<class 'Warning'>,) were emitted.
FAILED tests/test_source_cli.py::test_cli_alias_arg[True] - AttributeError: type object 'CliApp' has no attribute 'serialize'
FAILED tests/test_source_cli.py::test_cli_alias_arg[False] - AttributeError: type object 'CliApp' has no attribute 'serialize'
FAILED tests/test_source_cli.py::test_cli_alias_nested_arg[True] - SystemExit: 2
FAILED tests/test_source_cli.py::test_cli_alias_nested_arg[False] - SystemExit: 2
FAILED tests/test_source_cli.py::test_cli_bool_flags[True] - AttributeError: type object 'CliApp' has no attribute 'serialize'
FAILED tests/test_source_cli.py::test_cli_bool_flags[False] - AttributeError: type object 'CliApp' has no attribute 'serialize'
FAILED tests/test_source_cli.py::test_cli_subcommand_invalid_abbrev - Failed: DID NOT RAISE <class 'pydantic_settings.exceptions.SettingsError'>
FAILED tests/test_source_cli.py::test_cli_kebab_case - AttributeError: type object 'CliApp' has no attribute 'serialize'
FAILED tests/test_source_cli.py::test_cli_serialize_positional_args - AttributeError: type object 'CliApp' has no attribute 'serialize'
FAILED tests/test_source_cli.py::test_cli_app_with_separate_parser - SystemExit: 2
FAILED tests/test_source_cli.py::test_cli_serialize_non_default_values - AttributeError: type object 'CliApp' has no attribute 'serialize'
FAILED tests/test_source_cli.py::test_cli_serialize_ordering - AttributeError: type object 'CliApp' has no attribute 'serialize'
FAILED tests/test_source_cli.py::test_cli_decoding - pydantic_settings.exceptions.SettingsError: error parsing value for field "...
```

**Comment by hramezani** [comment]
Thanks @chbndrhnns for the issue.

Have you tried `make install`? can you test it in a fresh env?

**Comment by chbndrhnns** [comment]
I was looking for the contribution guide ;) `make install; make test` did the trick for me.
